---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-argo-app-2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ali-rabiei1989/argocd-tutorial.git
    targetRevision: tutorial
    path: v19-my-custom-scenario/add-cluster/multi-cluster-app
  destination:
    name: dev-cluster
    namespace: argo-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false