apiVersion: v1

kind: Secret

metadata:

  name: dev-cluster

  namespace: argocd

  labels:

    argocd.argoproj.io/secret-type: cluster

type: Opaque

stringData:

  name: dev-cluster

  server: 192.168.255.1:64430

  config: |

    {

      "bearerToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6Il8yRDdxaUZ6V3pJRmcyVHVsUHBzcUxrOG9PdGdqcWFHaTJ2UFFHM0x5NDQifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJhcmdvLWFwcCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJhcmdvY2QtbWFuYWdlci10b2tlbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJhcmdvY2QtbWFuYWdlciIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImY1ZDQ3Mzc3LTgxNDAtNDIwMy05YzkyLWY2MWJlMWQ3YzFkOCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDphcmdvLWFwcDphcmdvY2QtbWFuYWdlciJ9.TuOSEjT2UlM8cUBw6Xs70CvXt1cfq0jztVB3JFMKnCz7zQTbr-TkvoBbObZe-EN--uwOexBlbxVcyXRDRkgLRgfegBvSb07K_PRfXYA25c02aMgWElCzkp-TWioT7d3Inwx0iigxQtP728PRqvIIwokKZkn7ersnX-SftTY1JpWATJ-0Plz1A8Rb_y9E0J7ikvTPfOV3f_LvTOgX5nE9nzlIeE291UhksWhCp7cMMiqOq4VpPXAT8SK6PKbO-kKsIrimIjpvTDnwWCVoQhm6vxC976fNK6OaPHfxiIVoyiqMhAZnNi_DadTecuiZ_8claBPOauAiX_aYTRk6spvCGQ",

      "tlsClientConfig": {

        "caData": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJY2pWOWFBZWNhNll3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBMk1USXdPVEE0TWpaYUZ3MHpOakEyTURrd09URXpNalphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUM1L0hWTG5hc25NZ3pqU1JHeXBZT0dnSWFHZFQ4VFFaZnk4cGNIOUE4K3NmWC9YT1RFMmhuL09iUXMKOVlVdkZlMWM5cjNXRXdRV0x5alRkekJ3Z3QrSEVwRFVUbmdReG05YVRNSGFPZ1RzWENmMlpUSDlybWh3UG0vZQpIS1YxOFNYZXlnVXRkdUJiOU5ac2J0NGU1RWhEanJjVHpYYjZhaHkwMFkyNDh4dTZOWkdJQWM2SlgrYmsxYjdQClRySmdkL1E3ZFFabHJHSnZLMGZwdk9TUjlmbUs3WVdNNFFLSmhEb1lqZkJFZVF2dDJmejVKQ2ZvcTFaTnl6dWIKRmF3K2NjR1Y2L1E2SVRwTDdEKzJtdmxHbkFpMyt3d05QcTk3NHBrSmJKZUcxV3F0WlFydVZianhwSU9tVXRESApSdkxzYzZqaFZGT2lvQkN0RGlEOGJPNXVsQUhYQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTNEVzODlrMDB4cjJnS2k5K3M1MWFPM0tsUDlEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQnI3aGNDc2h5agpNMUZWWGgwRVdWZUUrR3VRV0VJUXlxTnJXcXVFUkVQN3dYbXZLNlQvL3BLaGtCUXVmMEFDSjgyc0tXcWMxUXA3CjNzK1lKYmQ2TDRDVUdabXZaNHJYeWM5R25XTlVtU3E1UmNqZzJyRGdDc3Bhc3BUZDVLdWF3WFBjU1hNdmtmNE8KTUQzd1ZTZWJ5WTZaQlk5d3NSSGR0Qlc3T3h4eTJZMm9XdXB0N2pwYXFSaWY5U0dyMWU0Y3k0b2xnYkRUYmVCVgpYV1BjL2NEVkVieHZsZnJiQjY5K3VPQVJuZG5UMXlPQURxZ0dLdXpQQ3N4cHpkcFNlN2t3S3JySzFpdFFPNU52ClNwR0YwTGQ4UmZwakVWZlo3TFhCb3NTSGVqWVhJK2YyTCs4MUdmbEswZEZkSUpPSHB3S1B5aStSdFFwUS9WMUoKN0FpbEVUVmNKRnFBCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"

      }

    }