apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate-pre
spec:
  args:
  - name: service-name
  metrics:
    - name: success-rate-pre
      provider:
        job:
          spec:
            template:
              metadata:
                labels:
                  analysis: pre-promotion  
              spec:
                containers:
                - name: success-rate-pre-cntr
                  image: docker.io/library/web-tester:v3
                  command:
                    [sh, /tester.sh, http://preview.analysis-bluegreen.svc]
                  imagePullPolicy: Never
                restartPolicy: Never
