---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ali-rabiei1989/argocd-tutorial.git
    targetRevision: tutorial
    path: v19-my-custom-scenario/AppOfApps
  destination:
    server: https://kubernetes.default.svc
    namespace: my-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true