---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: git-gen-files-appset
  namespace: argocd
spec:
  goTemplateOptions: ['missingkey=error']
  generators:
    - git:
        repoURL: https://github.com/ali-rabiei1989/argocd-tutorial.git
        revision: tutorial
        files:
          - path: v19-my-custom-scenario/applicationset/git-generator-files/nginx/**/config.yaml
  template:
    metadata:
      name: '{{app.name}}-nginx-app'
      namespace: argocd
    spec:
      project: '{{app.project}}'
      source:
        repoURL: https://github.com/ali-rabiei1989/argocd-tutorial.git
        targetRevision: '{{app.branch}}'
        path: '{{app.path}}'
      destination:
        server: '{{app.cluster}}'
        namespace: '{{app.ns}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=false
          - CreateNamespace=true
    