apiVersion: v1
kind: ConfigMap
metadata:
  name: rolling-update-v1-cm
  namespace: rolling-update
data:
  index.html: |
    <html>
      <body>
        <h1>Welcome to Nginx v1</h1>
      </body>
    </html>
--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: rolling-update-v2-cm
  namespace: rolling-update
data:
  index.html: |
    <html>
      <body>
        <h1>Welcome to Nginx v2</h1>
      </body>
    </html>
   
